export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body style={{overflow: "hidden", background: "#f3f4f6"}}>{children}</body>
      </html>
    )
  }
  